            "sharing": {
                "all": ["facebook", "google", "twitter", "weibo", "instapaper", "github", "telegram", "linkedin"],
                "facebook": false,
                "google": false,
                "github": true,
                "github_link": "https://github.com/syauqi-alias",
                "telegram": false,
                "telegram_link": "https://t.me",
                "instapaper": false,
                "twitter": false,
                "vk": false,
                "weibo": false,
                "linkedin": true, 
                "linkedin_link": "https://www.linkedin.com/in/syauqi-alias/"
            },
